name: "Release"
on:
  release:
    types:
      - released
      
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Update version
        uses: ./release
      - uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
          message: "release ${{ github.event.release.tag_name }}"
          new_branch: "master"
  
  publish-docs:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: etd.inc