name: "Release"
on:
  release:
    types:
      - released

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Update version
        run: python3 main.py
      - uses: EndBug/add-and-commit@v8
        with:
          default_author: github_action
          message: "release ${{ github.event.release.tag_name }}"
